version: '3.8'

services:
  dolibarr:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./dolibarr_data:/var/www/html/dolibarr/documents
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
